[build]
base = "client/"
environment = { DATABASE_NAME = "server", DATABASE_USERNAME = "miguel_master", DATABASE_PASSWORD = "Miguel93500" }
# Default build command.
command = "npm install"
command = "npm run build"
command = "cp -R ./dist/client/ ../server/public/"
command = "cd server"
command = "npm install"
command = "npm start"